
import "./globals.css";
import TopHeader from "@/components/common/TopHeader";
import MainHeader from "@/components/common/MainHeader";
import Footer from "@/components/common/Footer";


export const metadata = {
  title: "HDD - India",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head >
<div>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet" />
</div>

      </head>
      <body className='font-Open '>
        <TopHeader/>
        <MainHeader/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
